apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: 853963783084.dkr.ecr.ap-northeast-2.amazonaws.com/backend:81
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m" # CPU 요청량을 추가합니다.
