apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "karpenter.sh/provisioner-name"
                  operator: "In"
                  values:
                  - "b3o-tools-ng-20240313111727172700000016"
      containers:
      - name: springboot-app
        image: 853963783084.dkr.ecr.ap-northeast-2.amazonaws.com/backend:100
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
          requests:
            cpu: 600m
            memory: 512Mi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 40"]
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 20
          timeoutSeconds: 30
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
      readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/springboot-app-ingress_springboot-app-service_8080
      terminationGracePeriodSeconds: 60
