apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-react-app
  template:
    metadata:
      labels:
        app: nginx-react-app
    spec:
      serviceAccount: s3-access-sa-web
      containers:
      - name: nginx-react-app
        image: 853963783084.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:116
        ports:
        - containerPort: 80
      provision: karpenter
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: react-app-config

