apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-react-app-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-react-app
  template:
    metadata:
      labels:
        app: nginx-react-app
    spec:
      serviceAccount: s3-access-sa-web
      containers:
      - name: nginx-react-app
        image: 853963783084.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:117
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}

